[workspace]
members = ["./streamdeck", "./streamdeck-gui/src-tauri"]

[package]
name = "streamdeck-control"
version = "0.1.0"
edition = "2021"

[dependencies]
hidapi = "2"
image = "0.25.2"
rand = "0.8"